import 'package:conferenceapp/agenda/repository/talks_repository.dart';
import 'package:conferenceapp/model/agenda.dart';
import 'package:conferenceapp/model/author.dart';
import 'package:conferenceapp/model/room.dart';
import 'package:conferenceapp/model/talk.dart';

class MockTalksRepository implements TalkRepository {
  @override
  Stream<List<Talk>> talks() => Stream.fromIterable(Iterable.castFrom(_talks));
  Stream<Talk> talk(id) => Stream.fromFuture(Future.value(_talks[0]));

  @override
  void refresh() {
    // TODO: implement refresh
  }
}

final _rA = Room('A', '0');
final _rB = Room('B', '1');

final _authors = [
  Author(
    '1',
    'Matilde Petrus',
    'Cross-group intangible collaboration',
    'Financial Advisor',
    'Bamity',
    'https://robohash.org/velitvitaetempora.bmp?size=100x100&set=set1',
  ),
  Author(
    '2',
    'Fancy Colston',
    'Open-architected 24 hour infrastructure',
    'Business Systems Development Analyst',
    'Overhold',
    'https://robohash.org/illumfugamolestias.bmp?size=100x100&set=set1',
  ),
  Author(
    'Linnea Cahen',
    'Seamless upward-trending productivity',
    'VP Marketing',
    'Namfix',
    'https://robohash.org/autculparepellendus.png?size=100x100&set=set1',
    '3',
  ),
  Author(
    'Friedrick Pleven',
    'Programmable hybrid support',
    'Office Assistant III',
    'Tampflex',
    'https://robohash.org/remdelenititempore.bmp?size=100x100&set=set1',
    '4',
  ),
  Author(
    'Renaud Garrique',
    'Adaptive radical framework',
    'Nuclear Power Engineer',
    'Mat Lam Tam',
    'https://robohash.org/consequunturaliasquidem.jpg?size=100x100&set=set1',
    '5',
  ),
  Author(
    'Meta Le Merchant',
    'Organized multimedia frame',
    'Technical Writer',
    'Bitchip',
    'https://robohash.org/utpraesentiumsint.png?size=100x100&set=set1',
    '6',
  ),
  Author(
    'Nicola Casbolt',
    'Synchronised contextually-based collaboration',
    'Senior Quality Engineer',
    'Veribet',
    'https://robohash.org/modiexercitationemrerum.bmp?size=100x100&set=set1',
    '7',
  ),
  Author(
    'Yasmeen Pietersen',
    'Vision-oriented tangible ability',
    'Web Designer II',
    'Lotlux',
    'https://robohash.org/quisquoet.png?size=100x100&set=set1',
    '8',
  ),
  Author(
    'Wait Greedyer',
    'Persevering methodical process improvement',
    'Analyst Programmer',
    'Otcom',
    'https://robohash.org/quiasperioresoccaecati.bmp?size=100x100&set=set1',
    '9',
  ),
  Author(
    '10',
    'Arlee Yashaev',
    'Fundamental upward-trending capacity',
    'Sales Associate',
    'Domainer',
    'https://robohash.org/voluptateofficiadeleniti.bmp?size=100x100&set=set1',
  ),
  Author(
    '11',
    'Seymour Chase',
    'Fully-configurable exuding time-frame',
    'Legal Assistant',
    'Solarbreeze',
    'https://robohash.org/delectusadolorem.jpg?size=100x100&set=set1',
  ),
  Author(
    '12',
    'Ebonee Benardette',
    'Focused disintermediate database',
    'Environmental Specialist',
    'Stronghold',
    'https://robohash.org/eteossuscipit.jpg?size=100x100&set=set1',
  ),
  Author(
    '13',
    'Blisse Scutts',
    'Virtual attitude-oriented application',
    'Graphic Designer',
    'Subin',
    'https://robohash.org/etdistinctiovitae.png?size=100x100&set=set1',
  ),
  Author(
    '14',
    'Andrea Milburn',
    'Advanced stable leverage',
    'Speech Pathologist',
    'It',
    'https://robohash.org/facereisterepudiandae.png?size=100x100&set=set1',
  ),
  Author(
    '15',
    'Hilarius Punter',
    'Future-proofed eco-centric initiative',
    'VP Accounting',
    'Ronstring',
    'https://robohash.org/utautiusto.png?size=100x100&set=set1',
  ),
  Author(
    '16',
    'Lindsey Senton',
    'Networked regional database',
    'VP Accounting',
    'Stronghold',
    'https://robohash.org/repudiandaedoloremquedelectus.png?size=100x100&set=set1',
  ),
  Author(
    '17',
    'Addi Northbridge',
    'Expanded cohesive standardization',
    'Cost Accountant',
    'Stronghold',
    'https://robohash.org/evenietsaepeut.bmp?size=100x100&set=set1',
  ),
  Author(
    '18',
    'Alexandrina Kinglake',
    'Secured zero defect help-desk',
    'Accounting Assistant IV',
    'Prodder',
    'https://robohash.org/occaecativoluptatestemporibus.png?size=100x100&set=set1',
  ),
  Author(
    '19',
    'Dalila Penner',
    'Synergized interactive hardware',
    'Legal Assistant',
    'Alpha',
    'https://robohash.org/ametoccaecatimaiores.png?size=100x100&set=set1',
  ),
  Author(
    '20',
    'Martino Ansley',
    'Optimized context-sensitive archive',
    'Product Engineer',
    'It',
    'https://robohash.org/autestculpa.jpg?size=100x100&set=set1',
  ),
  Author(
    '21',
    'Aymer Yarrington',
    'Multi-lateral well-modulated budgetary management',
    'Staff Accountant IV',
    'Domainer',
    'https://robohash.org/quiareprehenderitsed.jpg?size=100x100&set=set1',
  ),
  Author(
    '22',
    'Sam Saxby',
    'Reverse-engineered attitude-oriented paradigm',
    'Director of Sales',
    'Ronstring',
    'https://robohash.org/nisiexplicabonon.png?size=100x100&set=set1',
  ),
  Author(
    '23',
    'Kermy Morigan',
    'Up-sized clear-thinking archive',
    'Electrical Engineer',
    'Bigtax',
    'https://robohash.org/expeditasimiliqueet.jpg?size=100x100&set=set1',
  ),
  Author(
    '24',
    'Sophia Ragg',
    'Mandatory dynamic implementation',
    'Tax Accountant',
    'Sonair',
    'https://robohash.org/evenietnonaut.bmp?size=100x100&set=set1',
  ),
  Author(
    '25',
    'Gracie Epp',
    'Multi-channelled executive synergy',
    'Geological Engineer',
    'Veribet',
    'https://robohash.org/sittemporibusvoluptatum.png?size=100x100&set=set1',
  ),
  Author(
    '26',
    'Fields Finnick',
    'Compatible demand-driven orchestration',
    'Quality Control Specialist',
    'Viva',
    'https://robohash.org/autvoluptatemlabore.png?size=100x100&set=set1',
  ),
  Author(
    '27',
    'Haze Cliffe',
    'Ameliorated context-sensitive flexibility',
    'Social Worker',
    'Flexidy',
    'https://robohash.org/utmolestiaeest.png?size=100x100&set=set1',
  ),
  Author(
    '28',
    'Kasper Jermey',
    'Fully-configurable interactive implementation',
    'Tax Accountant',
    'Rank',
    'https://robohash.org/doloremquedelenitipossimus.jpg?size=100x100&set=set1',
  ),
  Author(
    '29',
    'Terence Moxom',
    'Synchronised encompassing installation',
    'Senior Financial Analyst',
    'Y-Solowarm',
    'https://robohash.org/fugitconsequaturfugiat.bmp?size=100x100&set=set1',
  ),
  Author(
    '30',
    'Aline Shevell',
    'Total fault-tolerant intranet',
    'Sales Associate',
    'Flexidy',
    'https://robohash.org/voluptatemanimiut.bmp?size=100x100&set=set1',
  ),
];

final _titles = [
  'Opening Keynote',
  'Making the most out of your Flutter development',
  '5 Guilt Free Flutter Tips',
  'Architect Patterns on Flutter',
  'Apply These 5 Secret Techniques To Improve Flutter',
  'How incorporate Flutter to an app with several millions of users',
  'The Time Is Running Out! Think About These 5 Ways To Change Your Flutter',
  'Accessibility on Flutter',
  'The Journey of Exposure with Flutter',
  'Geolocation and Maps on Flutter',
  'Adding a test layer to Flutter projects',
  'What happen if Google Flutter team disappear?',
  'Best Flutter Tips You Will Hear This Year',
  'What happen if Google Flutter team disappear?',
  'What happen if Google Flutter team disappear?',
  'What happen if Google Flutter team disappear?',
  'What happen if Google Flutter team disappear?',
  'Present & Future of Flutter',
  'Does FLUTTER, PROGRAMMING, MOBILE Sometimes Make You Feel Stupid?',
  'Present & Future of Flutter',
  'Present & Future of Flutter',
  'Present & Future of Flutter',
  'Present & Future of Flutter',
  'Present & Future of Flutter',
  'Present & Future of Flutter',
  'Present & Future of Flutter',
  'What happen if Google Flutter team disappear?',
  'What happen if Google Flutter team disappear?',
  'What happen if Google Flutter team disappear?',
  'What happen if Google Flutter team disappear?',
  'What happen if Google Flutter team disappear?',
  'Present & Future of Flutter',
];

final _talks = <Talk>[
  Talk(
      '0',
      _titles[0],
      [_authors[0], _authors[20]],
      'Description of the talk',
      DateTime(2020, 1, 23, 9, 0),
      DateTime(2020, 1, 23, 9, 45),
      _rA,
      TalkType.beginner),
  Talk(
      '2',
      _titles[2],
      [_authors[3]],
      'Description of the talk',
      DateTime(2020, 1, 23, 10, 0),
      DateTime(2020, 1, 23, 9, 45),
      _rA,
      TalkType.beginner),
  Talk(
      '3',
      _titles[3],
      [_authors[4]],
      'Description of the talk',
      DateTime(2020, 1, 23, 10, 0),
      DateTime(2020, 1, 23, 9, 45),
      _rB,
      TalkType.beginner),
  Talk(
      '4',
      _titles[4],
      [_authors[5]],
      'Description of the talk',
      DateTime(2020, 1, 23, 11, 0),
      DateTime(2020, 1, 23, 9, 45),
      _rA,
      TalkType.beginner),
  Talk(
      '5',
      _titles[5],
      [_authors[6]],
      'Description of the talk',
      DateTime(2020, 1, 23, 11, 0),
      DateTime(2020, 1, 23, 9, 45),
      _rB,
      TalkType.beginner),
  Talk(
      '6',
      _titles[6],
      [_authors[7]],
      'Description of the talk',
      DateTime(2020, 1, 23, 12, 0),
      DateTime(2020, 1, 23, 9, 45),
      _rA,
      TalkType.beginner),
  Talk(
      '7',
      _titles[7],
      [_authors[8]],
      'Description of the talk',
      DateTime(2020, 1, 23, 12, 0),
      DateTime(2020, 1, 23, 9, 45),
      _rB,
      TalkType.beginner),
  Talk(
      '8',
      _titles[8],
      [_authors[9]],
      'Description of the talk',
      DateTime(2020, 1, 23, 13, 0),
      DateTime(2020, 1, 23, 9, 45),
      _rA,
      TalkType.beginner),
  Talk(
      '9',
      _titles[9],
      [_authors[10]],
      'Description of the talk',
      DateTime(2020, 1, 23, 13, 0),
      DateTime(2020, 1, 23, 9, 45),
      _rB,
      TalkType.beginner),
  Talk(
      '10',
      _titles[10],
      [_authors[11]],
      'Description of the talk',
      DateTime(2020, 1, 23, 15, 0),
      DateTime(2020, 1, 23, 9, 45),
      _rA,
      TalkType.beginner),
  Talk(
      '11',
      _titles[11],
      [_authors[12]],
      'Description of the talk',
      DateTime(2020, 1, 23, 15, 0),
      DateTime(2020, 1, 23, 9, 45),
      _rB,
      TalkType.beginner),
  Talk(
      '12',
      _titles[12],
      [_authors[13]],
      'Description of the talk',
      DateTime(2020, 1, 23, 16, 0),
      DateTime(2020, 1, 23, 9, 45),
      _rA,
      TalkType.beginner),
  Talk(
      '13',
      _titles[13],
      [_authors[14]],
      'Description of the talk',
      DateTime(2020, 1, 23, 16, 0),
      DateTime(2020, 1, 23, 9, 45),
      _rB,
      TalkType.beginner),
  Talk(
      '15',
      _titles[15],
      [_authors[16]],
      'Description of the talk',
      DateTime(2020, 1, 23, 17, 0),
      DateTime(2020, 1, 23, 9, 45),
      _rA,
      TalkType.beginner),
  Talk(
      '16',
      _titles[16],
      [_authors[17]],
      'Description of the talk',
      DateTime(2020, 1, 23, 17, 0),
      DateTime(2020, 1, 23, 9, 45),
      _rB,
      TalkType.beginner),
  //Day2
  Talk(
      '17',
      _titles[17],
      [_authors[18]],
      'Description of the talk',
      DateTime(2020, 1, 24, 9, 0),
      DateTime(2020, 1, 23, 9, 45),
      _rA,
      TalkType.beginner),
  Talk(
      '19',
      _titles[19],
      [_authors[23]],
      'Description of the talk',
      DateTime(2020, 1, 24, 10, 0),
      DateTime(2020, 1, 23, 9, 45),
      _rA,
      TalkType.beginner),
  Talk(
      '20',
      _titles[20],
      [_authors[24]],
      'Description of the talk',
      DateTime(2020, 1, 24, 10, 0),
      DateTime(2020, 1, 23, 9, 45),
      _rB,
      TalkType.beginner),
  Talk(
      '21',
      _titles[21],
      [_authors[25]],
      'Description of the talk',
      DateTime(2020, 1, 24, 11, 0),
      DateTime(2020, 1, 23, 9, 45),
      _rA,
      TalkType.beginner),
  Talk(
      '22',
      _titles[22],
      [_authors[26]],
      'Description of the talk',
      DateTime(2020, 1, 24, 11, 0),
      DateTime(2020, 1, 23, 9, 45),
      _rB,
      TalkType.beginner),
  Talk(
      '23',
      _titles[23],
      [_authors[27]],
      'Description of the talk',
      DateTime(2020, 1, 24, 12, 0),
      DateTime(2020, 1, 23, 9, 45),
      _rA,
      TalkType.beginner),
  Talk(
      '24',
      _titles[24],
      [_authors[28]],
      'Description of the talk',
      DateTime(2020, 1, 24, 12, 0),
      DateTime(2020, 1, 23, 9, 45),
      _rB,
      TalkType.beginner),
  Talk(
      '25',
      _titles[25],
      [_authors[29]],
      'Description of the talk',
      DateTime(2020, 1, 24, 15, 0),
      DateTime(2020, 1, 23, 9, 45),
      _rA,
      TalkType.beginner),
  Talk(
      '26',
      _titles[26],
      [_authors[29]],
      'Description of the talk',
      DateTime(2020, 1, 24, 15, 0),
      DateTime(2020, 1, 23, 9, 45),
      _rB,
      TalkType.beginner),
  Talk(
      '27',
      _titles[27],
      [_authors[4]],
      'Description of the talk',
      DateTime(2020, 1, 24, 16, 0),
      DateTime(2020, 1, 23, 9, 45),
      _rA,
      TalkType.beginner),
  Talk(
      '28',
      _titles[28],
      [_authors[0]],
      'Description of the talk',
      DateTime(2020, 1, 24, 16, 0),
      DateTime(2020, 1, 23, 9, 45),
      _rB,
      TalkType.beginner),
  Talk(
      '29',
      _titles[29],
      [_authors[1]],
      'Description of the talk',
      DateTime(2020, 1, 24, 17, 0),
      DateTime(2020, 1, 23, 9, 45),
      _rA,
      TalkType.beginner),
];
