# update_fastlane

default_platform(:android)

platform :android do
desc "Submit a new build to Firebase App Distribution"
  lane :tst do
    firebase_app_distribution(
      app: ENV["FIREBASE_ANDROID_TEST_APP_ID"],
      apk_path: ENV["APK_PATH"],
      release_notes: ENV["CHANGELOG"],
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"]
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :prod do
    upload_to_play_store(
      track: 'internal',
      json_key: ENV["GOOGLE_SERVICE_ACCOUNT_KEY"],
      package_name: ENV["APP_ID"],
      aab: ENV["AAB_PATH"]
    )
  end
end
